// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoNameData

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NameDataServiceClient is the client API for NameDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NameDataServiceClient interface {
	RegistrarJugadas(ctx context.Context, in *Jugada, opts ...grpc.CallOption) (*RespuestaJugadas, error)
}

type nameDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNameDataServiceClient(cc grpc.ClientConnInterface) NameDataServiceClient {
	return &nameDataServiceClient{cc}
}

func (c *nameDataServiceClient) RegistrarJugadas(ctx context.Context, in *Jugada, opts ...grpc.CallOption) (*RespuestaJugadas, error) {
	out := new(RespuestaJugadas)
	err := c.cc.Invoke(ctx, "/grpc.NameDataService/RegistrarJugadas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameDataServiceServer is the server API for NameDataService service.
// All implementations must embed UnimplementedNameDataServiceServer
// for forward compatibility
type NameDataServiceServer interface {
	RegistrarJugadas(context.Context, *Jugada) (*RespuestaJugadas, error)
	mustEmbedUnimplementedNameDataServiceServer()
}

// UnimplementedNameDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNameDataServiceServer struct {
}

func (UnimplementedNameDataServiceServer) RegistrarJugadas(context.Context, *Jugada) (*RespuestaJugadas, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistrarJugadas not implemented")
}
func (UnimplementedNameDataServiceServer) mustEmbedUnimplementedNameDataServiceServer() {}

// UnsafeNameDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NameDataServiceServer will
// result in compilation errors.
type UnsafeNameDataServiceServer interface {
	mustEmbedUnimplementedNameDataServiceServer()
}

func RegisterNameDataServiceServer(s grpc.ServiceRegistrar, srv NameDataServiceServer) {
	s.RegisterService(&NameDataService_ServiceDesc, srv)
}

func _NameDataService_RegistrarJugadas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Jugada)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameDataServiceServer).RegistrarJugadas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.NameDataService/RegistrarJugadas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameDataServiceServer).RegistrarJugadas(ctx, req.(*Jugada))
	}
	return interceptor(ctx, in, info, handler)
}

// NameDataService_ServiceDesc is the grpc.ServiceDesc for NameDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NameDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.NameDataService",
	HandlerType: (*NameDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistrarJugadas",
			Handler:    _NameDataService_RegistrarJugadas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nameData.proto",
}
