// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: LiderJugador.proto

package ProtoLiderJugadores

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//PARTICIPAR DEL JUEGO
type Solicitud struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre    string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Participa bool   `protobuf:"varint,2,opt,name=participa,proto3" json:"participa,omitempty"`
}

func (x *Solicitud) Reset() {
	*x = Solicitud{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LiderJugador_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Solicitud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solicitud) ProtoMessage() {}

func (x *Solicitud) ProtoReflect() protoreflect.Message {
	mi := &file_LiderJugador_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solicitud.ProtoReflect.Descriptor instead.
func (*Solicitud) Descriptor() ([]byte, []int) {
	return file_LiderJugador_proto_rawDescGZIP(), []int{0}
}

func (x *Solicitud) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Solicitud) GetParticipa() bool {
	if x != nil {
		return x.Participa
	}
	return false
}

type RespuestaSolicitud struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre    string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Participa bool   `protobuf:"varint,2,opt,name=participa,proto3" json:"participa,omitempty"`
	Id        int32  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RespuestaSolicitud) Reset() {
	*x = RespuestaSolicitud{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LiderJugador_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaSolicitud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaSolicitud) ProtoMessage() {}

func (x *RespuestaSolicitud) ProtoReflect() protoreflect.Message {
	mi := &file_LiderJugador_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaSolicitud.ProtoReflect.Descriptor instead.
func (*RespuestaSolicitud) Descriptor() ([]byte, []int) {
	return file_LiderJugador_proto_rawDescGZIP(), []int{1}
}

func (x *RespuestaSolicitud) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *RespuestaSolicitud) GetParticipa() bool {
	if x != nil {
		return x.Participa
	}
	return false
}

func (x *RespuestaSolicitud) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

//INFOMAR ETAPAS
type Etapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumEtapa int32 `protobuf:"varint,1,opt,name=numEtapa,proto3" json:"numEtapa,omitempty"`
}

func (x *Etapa) Reset() {
	*x = Etapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LiderJugador_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Etapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etapa) ProtoMessage() {}

func (x *Etapa) ProtoReflect() protoreflect.Message {
	mi := &file_LiderJugador_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etapa.ProtoReflect.Descriptor instead.
func (*Etapa) Descriptor() ([]byte, []int) {
	return file_LiderJugador_proto_rawDescGZIP(), []int{2}
}

func (x *Etapa) GetNumEtapa() int32 {
	if x != nil {
		return x.NumEtapa
	}
	return 0
}

type RespuestaEtapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Afirmacion string `protobuf:"bytes,1,opt,name=afirmacion,proto3" json:"afirmacion,omitempty"`
}

func (x *RespuestaEtapa) Reset() {
	*x = RespuestaEtapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LiderJugador_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaEtapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaEtapa) ProtoMessage() {}

func (x *RespuestaEtapa) ProtoReflect() protoreflect.Message {
	mi := &file_LiderJugador_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaEtapa.ProtoReflect.Descriptor instead.
func (*RespuestaEtapa) Descriptor() ([]byte, []int) {
	return file_LiderJugador_proto_rawDescGZIP(), []int{3}
}

func (x *RespuestaEtapa) GetAfirmacion() string {
	if x != nil {
		return x.Afirmacion
	}
	return ""
}

//ESTADO DE JUEGO
type Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Id     int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Estado) Reset() {
	*x = Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LiderJugador_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_LiderJugador_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_LiderJugador_proto_rawDescGZIP(), []int{4}
}

func (x *Estado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Estado) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RespuestaEstado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Afirmacion string `protobuf:"bytes,1,opt,name=afirmacion,proto3" json:"afirmacion,omitempty"`
}

func (x *RespuestaEstado) Reset() {
	*x = RespuestaEstado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LiderJugador_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaEstado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaEstado) ProtoMessage() {}

func (x *RespuestaEstado) ProtoReflect() protoreflect.Message {
	mi := &file_LiderJugador_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaEstado.ProtoReflect.Descriptor instead.
func (*RespuestaEstado) Descriptor() ([]byte, []int) {
	return file_LiderJugador_proto_rawDescGZIP(), []int{5}
}

func (x *RespuestaEstado) GetAfirmacion() string {
	if x != nil {
		return x.Afirmacion
	}
	return ""
}

//ENVIAR JUGADAS
type Jugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugada int32 `protobuf:"varint,1,opt,name=jugada,proto3" json:"jugada,omitempty"`
	Id     int32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Jugada) Reset() {
	*x = Jugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LiderJugador_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugada) ProtoMessage() {}

func (x *Jugada) ProtoReflect() protoreflect.Message {
	mi := &file_LiderJugador_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugada.ProtoReflect.Descriptor instead.
func (*Jugada) Descriptor() ([]byte, []int) {
	return file_LiderJugador_proto_rawDescGZIP(), []int{6}
}

func (x *Jugada) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

func (x *Jugada) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RespuestaJugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Afirmacion string `protobuf:"bytes,1,opt,name=afirmacion,proto3" json:"afirmacion,omitempty"`
}

func (x *RespuestaJugada) Reset() {
	*x = RespuestaJugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LiderJugador_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaJugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaJugada) ProtoMessage() {}

func (x *RespuestaJugada) ProtoReflect() protoreflect.Message {
	mi := &file_LiderJugador_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaJugada.ProtoReflect.Descriptor instead.
func (*RespuestaJugada) Descriptor() ([]byte, []int) {
	return file_LiderJugador_proto_rawDescGZIP(), []int{7}
}

func (x *RespuestaJugada) GetAfirmacion() string {
	if x != nil {
		return x.Afirmacion
	}
	return ""
}

var File_LiderJugador_proto protoreflect.FileDescriptor

var file_LiderJugador_proto_rawDesc = []byte{
	0x0a, 0x12, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x41, 0x0a, 0x09, 0x53, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x22, 0x5a, 0x0a,
	0x12, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x75, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x05, 0x45, 0x74, 0x61,
	0x70, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x45, 0x74, 0x61, 0x70, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x45, 0x74, 0x61, 0x70, 0x61, 0x22, 0x30,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61,
	0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e,
	0x22, 0x30, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73,
	0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x31, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x66, 0x69, 0x72, 0x6d,
	0x61, 0x63, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x06, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x66,
	0x69, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x32, 0xf5, 0x01, 0x0a, 0x13, 0x4c,
	0x69, 0x64, 0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3e, 0x0a, 0x11, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x61, 0x72, 0x53, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x12, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x75, 0x64, 0x12, 0x33, 0x0a, 0x0e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x72, 0x45, 0x74,
	0x61, 0x70, 0x61, 0x73, 0x12, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x74, 0x61, 0x70,
	0x61, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x34, 0x0a, 0x0d, 0x45, 0x6e, 0x76, 0x69, 0x61,
	0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x33, 0x0a,
	0x0c, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x0c, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x1a, 0x15, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x45, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x42, 0x3b, 0x5a, 0x39, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x6f, 0x6e, 0x43, 0x72, 0x61, 0x73,
	0x74, 0x69, 0x76, 0x2f, 0x49, 0x4e, 0x46, 0x2d, 0x33, 0x34, 0x33, 0x2f, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_LiderJugador_proto_rawDescOnce sync.Once
	file_LiderJugador_proto_rawDescData = file_LiderJugador_proto_rawDesc
)

func file_LiderJugador_proto_rawDescGZIP() []byte {
	file_LiderJugador_proto_rawDescOnce.Do(func() {
		file_LiderJugador_proto_rawDescData = protoimpl.X.CompressGZIP(file_LiderJugador_proto_rawDescData)
	})
	return file_LiderJugador_proto_rawDescData
}

var file_LiderJugador_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_LiderJugador_proto_goTypes = []interface{}{
	(*Solicitud)(nil),          // 0: grpc.Solicitud
	(*RespuestaSolicitud)(nil), // 1: grpc.RespuestaSolicitud
	(*Etapa)(nil),              // 2: grpc.Etapa
	(*RespuestaEtapa)(nil),     // 3: grpc.RespuestaEtapa
	(*Estado)(nil),             // 4: grpc.Estado
	(*RespuestaEstado)(nil),    // 5: grpc.RespuestaEstado
	(*Jugada)(nil),             // 6: grpc.Jugada
	(*RespuestaJugada)(nil),    // 7: grpc.RespuestaJugada
}
var file_LiderJugador_proto_depIdxs = []int32{
	0, // 0: grpc.LiderJugadorService.IngresarSolicitud:input_type -> grpc.Solicitud
	2, // 1: grpc.LiderJugadorService.InformarEtapas:input_type -> grpc.Etapa
	6, // 2: grpc.LiderJugadorService.EnviarJugadas:input_type -> grpc.Jugada
	4, // 3: grpc.LiderJugadorService.EnviarEstado:input_type -> grpc.Estado
	1, // 4: grpc.LiderJugadorService.IngresarSolicitud:output_type -> grpc.RespuestaSolicitud
	3, // 5: grpc.LiderJugadorService.InformarEtapas:output_type -> grpc.RespuestaEtapa
	7, // 6: grpc.LiderJugadorService.EnviarJugadas:output_type -> grpc.RespuestaJugada
	5, // 7: grpc.LiderJugadorService.EnviarEstado:output_type -> grpc.RespuestaEstado
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_LiderJugador_proto_init() }
func file_LiderJugador_proto_init() {
	if File_LiderJugador_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_LiderJugador_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Solicitud); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LiderJugador_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaSolicitud); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LiderJugador_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Etapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LiderJugador_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaEtapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LiderJugador_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LiderJugador_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaEstado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LiderJugador_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LiderJugador_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaJugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LiderJugador_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_LiderJugador_proto_goTypes,
		DependencyIndexes: file_LiderJugador_proto_depIdxs,
		MessageInfos:      file_LiderJugador_proto_msgTypes,
	}.Build()
	File_LiderJugador_proto = out.File
	file_LiderJugador_proto_rawDesc = nil
	file_LiderJugador_proto_goTypes = nil
	file_LiderJugador_proto_depIdxs = nil
}
