// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ProtoLiderJugadores

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiderJugadorServiceClient is the client API for LiderJugadorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiderJugadorServiceClient interface {
	IngresarSolicitud(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*RespuestaSolicitud, error)
	InformarEtapas(ctx context.Context, in *Etapa, opts ...grpc.CallOption) (*RespuestaEtapa, error)
	EnviarJugadas(ctx context.Context, in *Jugada, opts ...grpc.CallOption) (*RespuestaJugada, error)
	EnviarEstado(ctx context.Context, in *Estado, opts ...grpc.CallOption) (*RespuestaEstado, error)
}

type liderJugadorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLiderJugadorServiceClient(cc grpc.ClientConnInterface) LiderJugadorServiceClient {
	return &liderJugadorServiceClient{cc}
}

func (c *liderJugadorServiceClient) IngresarSolicitud(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*RespuestaSolicitud, error) {
	out := new(RespuestaSolicitud)
	err := c.cc.Invoke(ctx, "/grpc.LiderJugadorService/IngresarSolicitud", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liderJugadorServiceClient) InformarEtapas(ctx context.Context, in *Etapa, opts ...grpc.CallOption) (*RespuestaEtapa, error) {
	out := new(RespuestaEtapa)
	err := c.cc.Invoke(ctx, "/grpc.LiderJugadorService/InformarEtapas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liderJugadorServiceClient) EnviarJugadas(ctx context.Context, in *Jugada, opts ...grpc.CallOption) (*RespuestaJugada, error) {
	out := new(RespuestaJugada)
	err := c.cc.Invoke(ctx, "/grpc.LiderJugadorService/EnviarJugadas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liderJugadorServiceClient) EnviarEstado(ctx context.Context, in *Estado, opts ...grpc.CallOption) (*RespuestaEstado, error) {
	out := new(RespuestaEstado)
	err := c.cc.Invoke(ctx, "/grpc.LiderJugadorService/EnviarEstado", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiderJugadorServiceServer is the server API for LiderJugadorService service.
// All implementations must embed UnimplementedLiderJugadorServiceServer
// for forward compatibility
type LiderJugadorServiceServer interface {
	IngresarSolicitud(context.Context, *Solicitud) (*RespuestaSolicitud, error)
	InformarEtapas(context.Context, *Etapa) (*RespuestaEtapa, error)
	EnviarJugadas(context.Context, *Jugada) (*RespuestaJugada, error)
	EnviarEstado(context.Context, *Estado) (*RespuestaEstado, error)
	mustEmbedUnimplementedLiderJugadorServiceServer()
}

// UnimplementedLiderJugadorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLiderJugadorServiceServer struct {
}

func (UnimplementedLiderJugadorServiceServer) IngresarSolicitud(context.Context, *Solicitud) (*RespuestaSolicitud, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngresarSolicitud not implemented")
}
func (UnimplementedLiderJugadorServiceServer) InformarEtapas(context.Context, *Etapa) (*RespuestaEtapa, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InformarEtapas not implemented")
}
func (UnimplementedLiderJugadorServiceServer) EnviarJugadas(context.Context, *Jugada) (*RespuestaJugada, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarJugadas not implemented")
}
func (UnimplementedLiderJugadorServiceServer) EnviarEstado(context.Context, *Estado) (*RespuestaEstado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarEstado not implemented")
}
func (UnimplementedLiderJugadorServiceServer) mustEmbedUnimplementedLiderJugadorServiceServer() {}

// UnsafeLiderJugadorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiderJugadorServiceServer will
// result in compilation errors.
type UnsafeLiderJugadorServiceServer interface {
	mustEmbedUnimplementedLiderJugadorServiceServer()
}

func RegisterLiderJugadorServiceServer(s grpc.ServiceRegistrar, srv LiderJugadorServiceServer) {
	s.RegisterService(&LiderJugadorService_ServiceDesc, srv)
}

func _LiderJugadorService_IngresarSolicitud_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solicitud)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiderJugadorServiceServer).IngresarSolicitud(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.LiderJugadorService/IngresarSolicitud",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiderJugadorServiceServer).IngresarSolicitud(ctx, req.(*Solicitud))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiderJugadorService_InformarEtapas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Etapa)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiderJugadorServiceServer).InformarEtapas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.LiderJugadorService/InformarEtapas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiderJugadorServiceServer).InformarEtapas(ctx, req.(*Etapa))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiderJugadorService_EnviarJugadas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Jugada)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiderJugadorServiceServer).EnviarJugadas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.LiderJugadorService/EnviarJugadas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiderJugadorServiceServer).EnviarJugadas(ctx, req.(*Jugada))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiderJugadorService_EnviarEstado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Estado)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiderJugadorServiceServer).EnviarEstado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.LiderJugadorService/EnviarEstado",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiderJugadorServiceServer).EnviarEstado(ctx, req.(*Estado))
	}
	return interceptor(ctx, in, info, handler)
}

// LiderJugadorService_ServiceDesc is the grpc.ServiceDesc for LiderJugadorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiderJugadorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.LiderJugadorService",
	HandlerType: (*LiderJugadorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngresarSolicitud",
			Handler:    _LiderJugadorService_IngresarSolicitud_Handler,
		},
		{
			MethodName: "InformarEtapas",
			Handler:    _LiderJugadorService_InformarEtapas_Handler,
		},
		{
			MethodName: "EnviarJugadas",
			Handler:    _LiderJugadorService_EnviarJugadas_Handler,
		},
		{
			MethodName: "EnviarEstado",
			Handler:    _LiderJugadorService_EnviarEstado_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "LiderJugador.proto",
}
